Sforce8 Project Data/src/objects/AccountMaster__c.object
<CustomObject>
    <description>もっとも根っこのマスタデータとなる、このマスタの例えば部屋のグループ、料理のグループとしてオブジェクト化したものがタブの”お部屋”であり、”お料理”となる、参照関係にてこの基本のマスタデータ（商品マスタ）を参照する、これが陣屋の商品（もの）となる。</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <picklist>
            <picklistValues>
                <fullName>通常</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>前受付金</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>プラン</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>室料</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DPChange__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>#DP</label>
        <referenceTo>DP__c</referenceTo>
        <relationshipLabel>会計マスタ (#DP)</relationshipLabel>
        <relationshipName>Account71c4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field10__c</fullName>
        <label>小計割引／割増</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field11__c</fullName>
        <label>ﾌﾘｰ宣言</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field12__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お部屋</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountmasterVXNd</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field13_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>同一メニューで単価の異なるマスタをつなげるため、たとえば、朝食の単価¥2,000、¥3,000の切り替えのため</inlineHelpText>
        <label>$会計マスタ</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>Accountb142_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お料理</label>
        <referenceTo>FoodMenu__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountMaster8nAn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field3__c</fullName>
        <externalId>true</externalId>
        <label>商品コード</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Field4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>リンクＤＰコード</label>
        <referenceTo>DP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountMasterKmH3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <label>単価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field6__c</fullName>
        <label>ｻﾌﾞ単価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>原価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field8__c</fullName>
        <label>単価2</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field9__c</fullName>
        <label>ｾｯﾄ宣言</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPChange__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>集計先変更定義</inlineHelpText>
        <label>#GP</label>
        <referenceTo>GP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountzeBO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genkaritsu__c</fullName>
        <formula>if ( StsTaxfee__c = &quot;0&quot; , if (Field5__c &lt;&gt; 0, Field7__c / SalesnoneTax__c , 1), 1 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>税ステータスが非課税のとき、原価/売価、課税は、原価/売価（税抜)</inlineHelpText>
        <label>$原価率</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KD__c</fullName>
        <label>KD表示文字背景色</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OES__c</fullName>
        <label>OES用ﾒﾆｭｰ</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計OP</label>
        <referenceTo>OP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountMasterSUow</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PLU__c</fullName>
        <label>PLUｺｰﾄﾞ</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profit__c</fullName>
        <formula>if (  StsTaxfee__c  = &quot;0&quot;,  SalesnoneTax__c  -  Field7__c ,  Field5__c -  Field7__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売価-原価、税ステータスありなら、売価/1.05-原価</inlineHelpText>
        <label>$粗利益</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SCP_5__c</fullName>
        <inlineHelpText>セットメニューのインデックス番号、セットメニュー群は最大50個まで</inlineHelpText>
        <label>SCP(5)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesnoneTax__c</fullName>
        <formula>if ( StsTaxfee__c = &quot;0&quot;, if ( MOD(Field5__c,(1 + TaxRateCal__c)) = 0, Field5__c /(1 + TaxRateCal__c), if ( ROUND(MOD(Field5__c,(1 + TaxRateCal__c)),2) &gt;= 0.30, ROUND(Field5__c /(1 + TaxRateCal__c),0), Field5__c /(1 + TaxRateCal__c) )), Field5__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>会計明細の$単価(税抜)</inlineHelpText>
        <label>$単価(税抜)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SpecialTax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>特別税</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StsTaxfee__c</fullName>
        <inlineHelpText>0: 課税 99:非課税</inlineHelpText>
        <label>税ｽﾃｰﾀｽ</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxRateCal__c</fullName>
        <formula>jmstRef__r.TaxRate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>消費税</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>名称1(ｶﾅ)</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X3_2__c</fullName>
        <label>名称3(漢2)</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X4_3__c</fullName>
        <label>名称4(漢3)</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>detail13__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>セットメニューに金額の内訳をセットする対象かどうかチェックを入れてください</inlineHelpText>
        <label>セット</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>nextitemcode__c</fullName>
        <formula>VALUE(  IF(TEXT(ActionType__c) == &quot;プラン&quot;, Mid(Field3__c, 2, Len(Field3__c)-1), Field3__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$商品コード</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>proftPer__c</fullName>
        <formula>1 -  Genkaritsu__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$粗利益率</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>名称2(漢1)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/DP__c.object
<CustomObject>
    <description>部門マスタ</description>
    <fields>
        <fullName>Field1__c</fullName>
        <externalId>true</externalId>
        <label>リンクＤＰコード</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会計DP</label>
    <nameField>
        <label>DP</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/GP__c.object
<CustomObject>
    <description>グループマスタ</description>
    <fields>
        <fullName>Field1__c</fullName>
        <externalId>true</externalId>
        <label>リンクＧＰコード</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>会計GP</label>
    <nameField>
        <label>GP</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/OP__c.object
<CustomObject>
    <description>会計カテゴリ、集計のくくりはリロケータブルとなる</description>
    <fields>
        <fullName>Field1__c</fullName>
        <inlineHelpText>関連名</inlineHelpText>
        <label>カテゴリ</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>会計OP</label>
    <nameField>
        <label>会計OP名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/classes/ProductSearch_Ctrl.cls
public with sharing class ProductSearch_Ctrl {

    // 画面に表示する情報を格納用変数
    public List<AccountMaster__c> oProductLst{get;private set;}
    // 商品DP選択リスト
    public List<Selectoption> dpOptionLst{get; private set;}
    public List<Selectoption> gpOptionLst{get; private set;}
//    public List<Selectoption> opOptionLst{get; private set;}
    /***************************
    * 定数定義を行う
    ****************************/
    // 画面データ処理ステータス変数
    private Enum PAGE_STATUS {INS,UPD,SEL,UPDSPEC}
    public PAGE_STATUS pageStatus{get;private set;}
    public Boolean isIns{get{return pageStatus == PAGE_STATUS.INS;}}
    public Boolean isUpd{get{return pageStatus == PAGE_STATUS.UPD;}}
    public Boolean isSel{get{return pageStatus == PAGE_STATUS.SEL;}}
    // 新規商品格納用クラス
    public AccountMaster__c newAccMst{get;set;} 
    // 会計種別：プラン
    public String ACTTYPE_PLAN{get{return CommConst.PROD_ACTION_TYPE_PL;}}
    
    public ProductSearch_Ctrl() {
        // パラメータ分析する
        initParam();
        // 格納変数を初期化する
        oProductLst = new List<AccountMaster__c>();
        
        // 商品分類選択リストを設定を行う
        dpOptionLst = new List<Selectoption>();
        gpOptionLst = new List<Selectoption>();
//      opOptionLst = new List<Selectoption>();
        for (DP__c s: [select id, name, Field1__c from DP__c order by Name limit 500]) dpOptionLst.add(new SelectOption(s.id, s.Name));
        for (GP__c s: [select id, name, Field1__c from GP__c order by Name limit 500]) gpOptionLst.add(new SelectOption(s.id, s.Name));
//      for (OP__c s: [select id, name, Field1__c from OP__c order by Name limit 500]) opOptionLst.add(new SelectOption(s.id, s.Name));
    }
    
    public void init() {
        
        this.queryInfo();
    }
    
    public void insertInit() {
        // 画面ページステータス設定を行う
        pageStatus = PAGE_STATUS.INS;
        newAccMst = new AccountMaster__c();
    }
    public void insertData() {
        try {
            insert newAccMst;
        } catch (Exception e) {
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, '新規作成が失敗しました。', e.getmessage()));
        }
        // 最新情報を再設定をこなう
        newAccMst = [select Id, Name, Field5__c, TaxRateCal__c, ServiceRate__c, SpecialTax__c, ActionType__c From AccountMaster__c where id = :newAccMst.Id][0];
        pageStatus = PAGE_STATUS.UPD;
    }
    
    public void cancelAct() {
        this.queryInfo();
    }
    /*
    // 引渡しパラメータ情報
    public String p_operWinEleId{get;private set;}
    public String p_operWinEleNm{get;private set;}
    public String p_operWinEleHidNm{get;private set;}
    public String p_operWinElePrice{get;set;}
    public String p_operWinEleNum{get;set;}
    public String p_operWinEleTax{get;set;}*/
    // 親のJSを呼び出し関数名
    public String p_operWinJsFunNm{get;private set;}
    // 検索条件：商品名
    public String c_productNm{get;set;}
    public String c_gpId{get;set;}
    public String c_dpId{get;set;}
//    public String c_opId{get;set;}
    
    // 引渡しパラメータ分析する
    private void initParam() {
        /*
        PageReference pageRef = ApexPages.currentPage();
        // 設定するID
        p_operWinEleId = pageRef.getParameters().get('lkid');
        p_operWinEleNm = pageRef.getParameters().get('lknm');
        p_operWinEleHidNm = pageRef.getParameters().get('lkhidnm');
        p_operWinElePrice = pageRef.getParameters().get('lprice');
        p_operWinEleNum = pageRef.getParameters().get('lnumber');
        p_operWinEleTax = pageRef.getParameters().get('ltaxRate');
        // window.oper.xxx function name
        p_operWinJsFunNm = pageRef.getParameters().get('operJs');
        */
        Cookie dpidCookie = ApexPages.currentPage().getCookies().get('_produ_dpid');
        if (dpidCookie != null) c_dpId = dpidCookie.getValue();
        Cookie gpidCookie = ApexPages.currentPage().getCookies().get('_produ_gpId');
        if (gpidCookie != null) c_gpId = gpidCookie.getValue();
    }
    
    private static final String SQL_HEADER = 'Select Id ,TaxRateCal__c ,Name, ServiceRate__c, SpecialTax__c, ActionType__c ' + 
                                             ',DPChange__c ,Field10__c ,Field11__c ,Field12__c ,Field13_del__c ,Field2__c ,Field3__c ,Field4__c ' +
                                             ',Field5__c ,Field6__c ,Field7__c ,Field8__c ,Field9__c ,GPChange__c ,Genkaritsu__c ,KD__c ,OES__c ,OP__c ,PLU__c ,Profit__c ,SCP_5__c ' +
                                             ',SalesnoneTax__c ,StsTaxfee__c ,X1__c ,X3_2__c ,X4_3__c ,detail13__c ,nextitemcode__c ,proftPer__c ' +
                                             ' From AccountMaster__c where name != null ';
    
    public void queryInfo() {
        
        // 画面ページステータス設定を行う
        pageStatus = PAGE_STATUS.SEL;
        
        // 検索条件を取得する
        String whereStr = this.getWhereStr();
        // 画面検索条件を設定されている場合
        if (!CommUtils.isBlank(c_productNm)) {
            whereStr += ' AND ( name Like \'%' + CommUtils.escStr(c_productNm) + '%\''; 
            whereStr += ' OR X1__c   Like \'%' + CommUtils.escStr(c_productNm) + '%\'';
            whereStr += ' OR X3_2__c Like \'%' + CommUtils.escStr(c_productNm) + '%\''; 
            whereStr += ' OR X4_3__c Like \'%' + CommUtils.escStr(c_productNm) + '%\' )';
        }
        
        String sqlstr = SQL_HEADER + whereStr + this.getComOrderStr();    
        
        oProductLst = Database.query(sqlstr);

        // 20120915 選択した検索条件はCookiesに維持する
        Cookie dpidCookie = new Cookie('_produ_dpid', c_dpId, null, -1, true);
        Cookie gpidCookie = new Cookie('_produ_gpId', c_gpId, null, -1, true);
        ApexPages.currentPage().setCookies(new Cookie[]{dpidCookie,gpidCookie});
    }
    private String getWhereStr() {
        String whereStr = '';
        
        // DP設定場合
        if (!CommUtils.isBlank(c_dpId)) {
            whereStr += ' AND Field4__c = :c_dpId ';
        }
        // GP設定場合
        if (!CommUtils.isBlank(c_gpId)) {
            whereStr += ' And GPChange__c = :c_gpId ';
        }
        // OP設定場合
//        if (!CommUtils.isBlank(c_opId)) {
//            whereStr += ' And OP__c = :c_opId ';
//        }
        return whereStr;
    }
    // 100件まで表示する
    private String getComOrderStr () {
        return ' order by Field4__c,OP__c, name limit 101 ';
    }
}