Sforce8 Project Data/src/objects/AccountMaster__c.object
<CustomObject>
    <description>もっとも根っこのマスタデータとなる、このマスタの例えば部屋のグループ、料理のグループとしてオブジェクト化したものがタブの”お部屋”であり、”お料理”となる、参照関係にてこの基本のマスタデータ（商品マスタ）を参照する、これが陣屋の商品（もの）となる。</description>
    <fields>
        <fullName>Field5__c</fullName>
        <label>単価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GPChange__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>集計先変更定義</inlineHelpText>
        <label>#GP</label>
        <referenceTo>GP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountzeBO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計OP</label>
        <referenceTo>OP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>AccountMasterSUow</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>名称2(漢1)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/BookingEstimateItem__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>商品の数量を入力してください</inlineHelpText>
        <label>数量</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GPChange__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>集計先変更定義</inlineHelpText>
        <label>#GP</label>
        <referenceTo>GP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>BookingEstimateItemzeBO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>会計OP</label>
        <referenceTo>OP__c</referenceTo>
        <relationshipLabel>会計マスタ</relationshipLabel>
        <relationshipName>BookingEstimateItemSUow</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>商品名称（または券名称）</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpTotal__c</fullName>
        <label>#合計金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <inlineHelpText>空欄のまま保存すると、会計商品で定義した単価が設定されます</inlineHelpText>
        <label>単価(税込)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>refAccountMaster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>商品を選択して下さい</inlineHelpText>
        <label>商品名</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemhSGP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>refBooking__c</fullName>
        <label>ご予約</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>予約見積明細</relationshipLabel>
        <relationshipName>BookingEstimateItemFgKu</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>予約見積明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>予約見積明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/GP__c.object
<CustomObject>
    <description>グループマスタ</description>
    <label>会計GP</label>
    <nameField>
        <label>GP</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/Lead__c.object
<CustomObject>
    <description>予約台帳

Booking object: for one relation delete
1. Field283 &quot;(X5food5__c * chu4__c) +&quot; delete
2. X5food5__c delete
3. 昼料理５の通貨型の項目を追加して、昼料理５の金額を入力して頂くこと
4. タンザクレポートの昼料５項目のreplce</description>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/OP__c.object
<CustomObject>
    <description>会計カテゴリ、集計のくくりはリロケータブルとなる</description>
    <fields>
        <fullName>AliasName__c</fullName>
        <label>AliasName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>会計OP</label>
    <nameField>
        <label>会計OP名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/classes/BridalEstimatepageController.cls
public class BridalEstimatepageController{

    public BridalEstimatepageController() 
    {
        Accountmasterdetails();
        contact=new contact();
        lead=new Lead__c();
    }


    public contact contact{set;get;}
    public Lead__c lead{set;get;}
   public class wrapper
   {
       public op__c opObject{set;get;}
       public integer rowindex{set;get;}
       public list<wrappersecond> lstAccMstr{set;get;}
       
   }
   
   public class wrappersecond
   {
       public AccountMaster__c lstAccMstr{set;get;}
       public string Comment{set;get;}
       public integer index{set;get;}
       public decimal Quantity{set;get;}
       public decimal amount{set;get;}
   }
   
   public class wrapperfirst
   {
       public op__c opObject{set;get;}
       public integer rowindex{set;get;}
       public list<wrapperAccMstr> lstAccMstr{set;get;}
       
   }
   public class wrapperAccMstr
   {
       public AccountMaster__c lstAccMstr{set;get;}
       public string Comment{set;get;}
       public integer index{set;get;}
       public decimal Quantity{set;get;}
       public decimal amount{set;get;}
   }
   
   
    public BridalEstimatepageController(ApexPages.StandardController controller) 
    {
        Accountmasterdetails();
        contact=new contact();
    }
    
    set<id> Opids=new set<id>();
    
    public void Accountmasterdetails()
    {
        integer i=0;
        integer j=0;
        for(AccountMaster__c ac:[select id,name,Field5__c,OP__c,GPChange__c from AccountMaster__c where GPChange__c!=:null and GPChange__r.name=:'ブライダル部門' ])
        {
            Opids.add(ac.OP__c);
        }
        system.debug('###########'+Opids.size());
        for(OP__c op:[select id,name,AliasName__c,(select id,name,Field5__c,OP__c,GPChange__c from OP__c.AccountMasterSUow__r where GPChange__c!=null and GPChange__r.name=:'ブライダル部門') from OP__c where id in:Opids and AliasName__c not in('お料理','お飲物')])
        {
            wrapper w=new wrapper();
            w.opObject=op;
            w.rowindex=lstwrap.size();
            w.lstAccMstr=new list<wrappersecond>();
            
            for(AccountMaster__c ac:op.AccountMasterSUow__r)
            {
                wrappersecond ws=new wrappersecond();
                ws.lstAccMstr=ac;
                ws.index=w.lstAccMstr.size();
                w.lstAccMstr.add(ws);
                i++;
            }           
            
            lstwrap.add(w);
        }
        
        for(OP__c opf:[select id,name,AliasName__c,(select id,name,Field5__c,OP__c,GPChange__c from OP__c.AccountMasterSUow__r where GPChange__c!=null and GPChange__r.name=:'ブライダル部門') from OP__c where id in:Opids and AliasName__c in('お料理','お飲物')])
        {
            wrapperfirst wf=new wrapperfirst();
            wf.opObject=opf;
            wf.rowindex=lstwrapfirst.size();
            wf.lstAccMstr=new list<wrapperAccMstr>();
            for(AccountMaster__c ac:opf.AccountMasterSUow__r)
            {
                wrapperAccMstr w=new wrapperAccMstr();                
                w.lstAccMstr=ac;
                w.index=wf.lstAccMstr.size();
                w.Quantity=null;
                wf.lstAccMstr.add(w);
                j++;
            }
             
            lstwrapfirst.add(wf);         
            
            
        }
    }
    
    public list<wrapper> lstwrap=new list<wrapper>();
    public list<wrapper> getdata()
    {
        return lstwrap;
    }
    
    public list<wrapperfirst> lstwrapfirst=new list<wrapperfirst>();
    public list<wrapperfirst> getdataStart()
    {
        return lstwrapfirst;
    }

    public decimal Subtotal{set;get;}
    public decimal Subtotal2{set;get;}
    public decimal FinalSum{set;get;}
    
    list<BookingEstimateItem__c> lstBridal=new list<BookingEstimateItem__c>();
    public string Testval{set;get;}
    public pagereference CopyData()
    {
        lstBridal.clear();
        
        for(wrapperfirst w:lstwrapfirst)
        {
            for(wrapperAccMstr wa:w.lstAccMstr)
            {
                system.debug('@@@@@@@@@'+wa.Quantity);
                if(wa.Quantity!=0)
                {
                    BookingEstimateItem__c b=new BookingEstimateItem__c();
                    b.ProductName__c=wa.lstAccMstr.name;
                    b.UnitPrice__c=wa.lstAccMstr.Field5__c;
                    b.Amount__c=wa.Quantity;
                    b.SpTotal__c=wa.amount;
                    b.Comment__c=wa.Comment;
                    b.refBooking__c=lead.id;
                    b.refAccountMaster__c=wa.lstAccMstr.id;
                    lstBridal.add(b);
                }
            }
        }
        try{
        if(lstBridal.size()>0)
        insert lstBridal;
        }
        catch(Exception ex)
        {
            apexpages.addmessage(new apexpages.message(ApexPages.Severity.ERROR, 'Error=='+ex));
        }
        return null;
    }
    
    public string rowindexmain{set;get;}
    public string rowin{set;get;}
    public void onChangefield5()
    {
        decimal total;
        Subtotal=0;
        integer row=integer.valueof(rowindexmain);
        integer rowi=integer.valueof(rowin);
        total=lstwrapfirst[row].lstAccMstr[rowi].lstAccMstr.field5__c*lstwrapfirst[row].lstAccMstr[rowi].quantity;
        lstwrapfirst[row].lstAccMstr[rowi].amount=total;
        
        for(wrapperfirst w:lstwrapfirst)
        {
            for(wrapperAccMstr ws:w.lstAccMstr)
            {
                if(ws.amount!=null)
                Subtotal+=ws.amount;
            }
        }
        if(Subtotal2!=null)
            FinalSum=Subtotal+Subtotal2;
        else
            FinalSum=Subtotal;
        
        
    }
    
    public void onChangequantity()
    {
        decimal total;
        Subtotal2=0;
        integer row=integer.valueof(rowindexmain);
        integer rowi=integer.valueof(rowin);       
        
        total=lstwrap[row].lstAccMstr[rowi].lstAccMstr.field5__c*lstwrap[row].lstAccMstr[rowi].quantity;
        lstwrap[row].lstAccMstr[rowi].amount=total;
        
        for(wrapper w:lstwrap)
        {
            for(wrappersecond ws:w.lstAccMstr)
            {
                if(ws.amount!=null)
                Subtotal2+=ws.amount;
            }
        }
        if(Subtotal!=null)
            FinalSum=Subtotal+Subtotal2;
        else
            FinalSum=Subtotal2;
        
    }
    

}