Sforce8 Project Data/src/objects/AccountAcount__c.object
<CustomObject>
    <description>*** Account relationship ***
----------------Customer
----------------    |
----------------    |
----------------    V
Pay Tran -------&gt;[Total Tran]&lt;------Item Tran


[ttotal.csv] Import
[ttotal02.csv] Import</description>
    <fields>
        <fullName>AmoutSpecialPrice__c</fullName>
        <label>特別税</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>割引金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field141__c</fullName>
        <label>営業日付</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field145__c</fullName>
        <label>レシートＮｏ．</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field147__c</fullName>
        <formula>VALUE(  Field114__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$売上計III（税抜）金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field148__c</fullName>
        <formula>DATE(VALUE(MID(Field53__c,1,4)),VALUE(MID(Field53__c,5,2)),VALUE(MID(Field53__c,7,2)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$会計日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Field151__c</fullName>
        <formula>VALUE(  Field116__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$売上計IV（税込）金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>伝票Ｎｏ．</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POSNo__c</fullName>
        <defaultValue>&apos;0001&apos;</defaultValue>
        <label>POSNo.</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relreserve__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ご予約</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>Account8Wls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SumSrvPriceExcTax__c</fullName>
        <label>サービス料（税抜）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SumSrvPriceIncTax__c</fullName>
        <label>サービス料（税込）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>frs__c</fullName>
        <label>予約会計</label>
        <referenceTo>RsvAccount__c</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>AccountYLM3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>relaccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>会計</relationshipLabel>
        <relationshipName>accountjvxI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>会計</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/AccountMaster__c.object
<CustomObject>
    <description>もっとも根っこのマスタデータとなる、このマスタの例えば部屋のグループ、料理のグループとしてオブジェクト化したものがタブの”お部屋”であり、”お料理”となる、参照関係にてこの基本のマスタデータ（商品マスタ）を参照する、これが陣屋の商品（もの）となる。</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <picklist>
            <picklistValues>
                <fullName>通常</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>前受付金</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>プラン</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>室料</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <label>単価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>原価</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductEnName__c</fullName>
        <label>商品名称（英）</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>会計商品</label>
    <nameField>
        <label>名称2(漢1)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/CommDefine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>FacilityCode__c</fullName>
        <label>施設コード</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POSNo__c</fullName>
        <defaultValue>&apos;0000&apos;</defaultValue>
        <label>POSNo.</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>共通定義</label>
</CustomObject>

Sforce8 Project Data/src/objects/Lead__c.object
<CustomObject>
    <description>予約台帳

Booking object: for one relation delete
1. Field283 &quot;(X5food5__c * chu4__c) +&quot; delete
2. X5food5__c delete
3. 昼料理５の通貨型の項目を追加して、昼料理５の金額を入力して頂くこと
4. タンザクレポートの昼料５項目のreplce</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field20__c</fullName>
        <label>マイクロ代</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field21__c</fullName>
        <label>飲み放題</label>
        <picklist>
            <picklistValues>
                <fullName>90分コース   ¥2400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120分コース ¥3500</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field23__c</fullName>
        <label>写真代</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/LeadIndex__c.object
<CustomObject>
    <description>予約インデックス情報を格納する</description>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>&apos;15:00&apos;</defaultValue>
        <description>HH:MM</description>
        <label>到着時刻</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>予約インデックス</label>
    <nameField>
        <displayFormat>I_{YYYY}_{0000000000}</displayFormat>
        <label>予約名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/Room__c.object
<CustomObject>
    <description>客室と宴会場などを定義</description>
    <fields>
        <fullName>Field5__c</fullName>
        <inlineHelpText>トイレは全客室あり、ただし、ウォシュレット付き／なしの区別のみ</inlineHelpText>
        <label>トイレ</label>
        <picklist>
            <picklistValues>
                <fullName>○</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <label>ベッド</label>
        <picklist>
            <picklistValues>
                <fullName>○</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>お部屋</label>
    <nameField>
        <label>お部屋</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/RsvAccount__c.object
<CustomObject>
    <description>会計メイン
本館、レストランなど別に営業日１日分の予約会計をある単位で、積み上げ集計した売上の一覧

予約会計名は営業日付となる</description>
    <fields>
        <fullName>Discount__c</fullName>
        <label>割引値引合計(税込)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <formula>(OccHiru__c   +  Occyuu__c)/2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>稼働率[部屋食]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Salesday__c</fullName>
        <formula>DATEVALUE(MID(Name,1,4) &amp; &quot;-&quot; &amp; MID(Name,5,2) &amp; &quot;-&quot; &amp; MID(Name,7,2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売上計上日</inlineHelpText>
        <label>営業日付</label>
        <type>Date</type>
    </fields>
    <label>売上</label>
    <nameField>
        <label>予約会計名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/objects/Tran1__c.object
<CustomObject>
    <description>*** Account relationship ***
----------------Customer
---------------- |
---------------- |
Pay Tran -------&gt;Total Tran&lt;------[Item Tran]

[titem.csv] Import
[titem02.csv] Import</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <description>普通の商品は　デフォルト値：通常で設定する、特別商品に対して、別々、商品種別に設定する
前受付金の場合、会計商品マスたに、価格はNull設定して、入力画面に自由入力する</description>
        <label>商品処理種別</label>
        <picklist>
            <picklistValues>
                <fullName>通常</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>前受付金</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field20__c</fullName>
        <label>単価</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field21__c</fullName>
        <label>数量</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field23__c</fullName>
        <label>合計金額</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field41__c</fullName>
        <formula>VALUE( Field23__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$合計金額（税込）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Field5__c</fullName>
        <label>商品名称（または券名称）</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品コード</label>
        <referenceTo>AccountMaster__c</referenceTo>
        <relationshipName>Tran1Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POSNo__c</fullName>
        <inlineHelpText>POSレジ番号</inlineHelpText>
        <label>POSNo.</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelAccount__c</fullName>
        <label>予約会計</label>
        <referenceTo>RsvAccount__c</referenceTo>
        <relationshipLabel>会計明細</relationshipLabel>
        <relationshipName>TitemYObe</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RowNo__c</fullName>
        <description>会計書のNo.項目</description>
        <label>RowNo.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceRate__c</fullName>
        <description>サービス料金（％）</description>
        <label>サービス料</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tankanonetax__c</fullName>
        <description>if ( Field7__r.StsTaxfee__c = &quot;0&quot;, if ( MOD(Field39__c,(1 + TaxRate__c)) = 0,Field39__c /(1 + TaxRate__c), if ( ROUND(MOD(Field39__c,(1 + TaxRate__c)),2) &gt;= 0.30, ROUND(Field39__c /(1 + TaxRate__c),0),Field39__c /(1 + TaxRate__c) )), Field39__c)

2012/07/04 四捨五入から切り上げ設定</description>
        <formula>/*if ( Field7__r.StsTaxfee__c = &quot;0&quot;, CEILING(Field39__c /(1 + TaxRate__c)), Field39__c) */
/*
    // 1:税込、サービス料抜き
    // 2:税込、サービス料込
    // 3:税抜、サービス料抜き
*/
Case ($Setup.CommDefine__c.UnitPriceDefKb__c ,
1, CEILING( Field39__c / ( 1 +  NULLVALUE (TaxRate__c, 0) ) ),
2, CEILING( Field39__c / ( (1 + NULLVALUE (TaxRate__c, 0) ) * ( 1 + NULLVALUE (ServiceRate__c, 0) ) ) ), 
3, Field39__c ,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>会計マスタの税ステータスが税額そのもののときは単価（税抜）の金額は単価そのものとする、端数処理について、端数が存在すれば切り上げ処理となっている。
***近似の0.3スライス</inlineHelpText>
        <label>$単価(税抜)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>消費税</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>会計明細</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>会計明細TranR#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sforce8 Project Data/src/classes/AccountPDFClass.cls
/**
* 会計書
* 会計書機能対応
**/
public with sharing class AccountPDFClass{
  // 施設コードにて、レポート改ページ定義を格納する
  private static final Map<String, Integer> pageMap;
  // 開始ページに詳細データ明細件数
  private static final Integer maxLineNums = 28;
  // 商品名表示言語
  private static final String lang_jp='jp';
  private static final String lang_en='en';
  public Boolean isShowEnName{get; private set;}
  // 統合印刷タイプ
  private static final String ROOM_ONLY = 'r';
  private static final String ROOM_FOOD = 'rf';
  // 分割NO設定値の格納
  private static final Set<String> splitNoSet;
  
  static {
    pageMap = new Map<String,Integer>{
      // hotel-continental　会社会計書PDF専用ページ
      '2'=>22,
      // JINYA会社DefaultPDF専用ページ
      '1'=>maxLineNums};
      
        /*Schema.DescribeFieldResult fieldResult = Tran1__c.SplitGroupNo__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        splitNoSet = new Set<String>();
        for( Schema.PicklistEntry f : ple) {
            splitNoSet.add(f.getValue());
        }*/
  }
  // 合計金額など集計用会計情報リスト
    private List<AccountAcount__c> account;
    // 会計明細情報を格納する
    private List<TranItem> tran;
    // 課税対象商品の売上金額合計を格納する
    private Decimal amoutIncTaxprice = 0;
    // サビース料金（税込）
    private Decimal amoutIncServicePrice = 0;
    // 特別税合計
    private Decimal amoutIncSpecialPrice = 0;
    // 割引合計
    private Decimal amoutIncDiscont = 0;
    // 前受付金の金額合計を格納する
    private Decimal amoutARprice = 0;
    // 税込前金額合計を格納する
    private Decimal amoutAllMoney = 0;
  // 一ページに最大格納できる明細レコード数
  // FirstPage [Default 29行]
    private Integer PAGE_FIRSTPG_BREAK_RSNUM = pageMap.get(CommDefine__c.getOrgDefaults().FacilityCode__c) == null ? maxLineNums : pageMap.get(CommDefine__c.getOrgDefaults().FacilityCode__c);
    // SecondPage以後 [Default 29行]
    private final Integer PAGE_NEXTPG_BREAK_RSNUM = 45;
    // 前頁から引渡パラメータ情報を維持する変数
    private final Map<String,String> parMap;

  // PDFページ毎の明細情報を格納用
  public List<OnePage> allPageList{get; private set;}
  public class OnePage {
    // startRsIndex：データ開始行目
    public OnePage () {
      onePageList = new List<TranItem>();
      currPages = 1;
    }
    // ページ内に追加するITEM
    public void addItem(TranItem item) {
      onePageList.add(item);
    }
    // 現在表示してページ数
    public Integer currPages{get;set;}
    public Boolean isFirstPage{get{
      return currPages == 1;
    }}
    // １ページ表示用データを格納
    public List<TranItem> onePageList{get; private set;}
  }
  /**
  * 初期化処理を行う
  **/
    public AccountPDFClass(ApexPages.StandardController controller){
      // パラメータ情報を取得する
      parMap = ApexPages.currentPage().getParameters();
        // 2012/10/22 URLから引渡パラメータ情報（明細行数設定がある場合、設定の行数で優先に設定する）
        String strPageSize = parMap.get('pgsize');
        if (!CommUtils.isBlank(strPageSize)) PAGE_FIRSTPG_BREAK_RSNUM = Integer.valueOf(strPageSize);
      // 2012/08/25 WSQ ADD
      String bulkid = parMap.get('bulkid');
      Set<Id> accIdSet = new Set<Id>();
      accIdSet.add(controller.getId());
      if (!CommUtils.isBlank(bulkId)) {
        String[] accIdLst = bulkId.split(',');
        for (String s : accIdLst) {accIdSet.add(s);}
      }
      // 2012/10/25 WSQ ADD 商品名：英語を表示フラグ
      isShowEnName = parMap.get('language') != lang_en ? false : true;
    // 2013/01/26 ADD 印刷種別の取得
    String printType = parMap.get('pType');
    // 2013/01/29 ADD GROUP設定によて、詳細印刷、表示を行う
    Boolean isGroupShowFlg = parMap.get('g') == '1' ? true : false;
    String groupNo = parMap.get('gno');
    
      //Set<Date> rateGetDaySet = new Set<Date>();
        //query '会計' current page
        account = [
            select id, name, POSNo__c, relaccount__r.name, Field141__c, Discount__c,
                AmoutSpecialPrice__c,SumSrvPriceExcTax__c,SumSrvPriceIncTax__c,
                Field145__c, Field147__c, Field148__c, Field151__c, Relreserve__c, Relreserve__r.RecordTypeId,
                relaccount__r.Account.Name,      // 会計書の請求書欄の請求先名は取得の機能追加　
                            // 会計の発行日
                Relreserve__r.EntryTime__c          // 会計の予約の到着日で、発行日として表示する
            from AccountAcount__c
            //where id = :controller.getId()
            where id in :accIdSet
            Order By frs__r.Name, Name      // 売上日/会計日で並べ順
            ];
    // 総税込金額を合計する
    for (AccountAcount__c acc: account) {
      // 総計金額を計算する
      amoutAllMoney += CommUtils.nullToZero(acc.Field151__c);
      // 割引額を合計する
      amoutIncDiscont += CommUtils.nullToZero(acc.Discount__c);
      // 特別税金が存在する場合、明細へ追加する
      if (acc.AmoutSpecialPrice__c != null && acc.AmoutSpecialPrice__c > 0) {
        amoutIncSpecialPrice += acc.AmoutSpecialPrice__c;
      }
    }
    // 2013/01/27 ADD/EDIT
    String tranQuery = 'select id, name, RowNo__c, Field5__c, Tankanonetax__c, Field20__c, Field21__c,ServiceRate__c ,Field7__r.ProductEnName__c,Field41__c,TaxRate__c, ActionType__c, Field23__c, RelAccount__r.Salesday__c, SpecialTax__c   from Tran1__c ';
        tranQuery += ' where Field1__c in :accIdSet  ';
        if (printType == ROOM_ONLY) {
          tranQuery += ' And ActionType__c = \'' + CommConst.PROD_ACTION_TYPE_RP + '\'';
        } else if (printType == ROOM_FOOD) {
          tranQuery += ' And ( ActionType__c = \'' + CommConst.PROD_ACTION_TYPE_RP + '\')';
          //tranQuery += '     OR ActionType__c = \'' + CommConst.PROD_ACTION_TYPE_MO + '\')';
        } else if (isGroupShowFlg) {
          // 分割出力
          if (splitNoSet.contains(groupNo)) {
              tranQuery += ' And SplitGroupNo__c = :groupNo ';
          } else {
            tranQuery += ' And SplitGroupNo__c = null ';
          }
        } else {
          // ALLの場合、集計対象のデータだけ、レポートへ出力する
          tranQuery += ' And Accountoutside__c =1 And InvoiceNoShowFlg__c != true ';
        }
        // Order By Add
        if (!isGroupShowFlg) {
          tranQuery += ' Order By RelAccount__r.Name, Name ';
        } else {
            tranQuery += ' Order By SplitGroupNo__c, RelAccount__r.Name, Name ';
        }
System.debug('tranQuery:::' + tranQuery);
        //query '会計明細' current page
        /*
        List<Tran1__c> tranRsLst = [
                select id, name, RowNo__c, Field5__c, Tankanonetax__c, Field20__c, Field21__c,ServiceRate__c ,Field7__r.ProductEnName__c,
                    Field41__c,TaxRate__c, ActionType__c, Field23__c, RelAccount__r.Salesday__c, SpecialTax__c
                from Tran1__c
                //where Field1__c = :account.id
                where Field1__c in :accIdSet
                And Accountoutside__c =1 And InvoiceNoShowFlg__c != true
                Order By RelAccount__r.Name, Name];*/
        
    // 明細単位の合計情報
    Decimal amoutAllMoneyDetail = 0;
    Decimal amoutIncDiscontDetail = 0;
    Decimal amoutIncSpecialPriceDetail = 0;
    //query '会計明細' current page
    tran = new List<TranItem>();
        for(Tran1__c sobj : DataBase.query(tranQuery)) {
          // 前受付金の商品する場合
          if (sobj.ActionType__c == CommConst.PROD_ACTION_TYPE_AR) {
            amoutARprice += CommUtils.nullToZero(sobj.Field23__c);
            continue;
          }
/* 20121005修正を行う（商品単価多目意味機能対応） */
            Decimal unitPrice = CommUtils.nullToZero(sobj.Field20__c);  // 商品単価
            Decimal qty = CommUtils.nullToZero(sobj.Field21__c);
            CommUtils.ProductInfo priceInfo = new CommUtils.ProductInfo();
            priceInfo.process(unitPrice, qty , sobj.TaxRate__c, sobj.ServiceRate__c);

            // 税率は0以上の場合、該当合計金額は課税対象です[商品本体の単価＊数量（税込）= 税込金額]
//            if(sobj.TaxRate__c > 0) amoutIncTaxprice += CommUtils.nullToZero(sobj.Field20__c) * CommUtils.nullToZero(sobj.Field21__c);
            TranItem item = new TranItem(sobj, tran.size()+1);
            //if(sobj.TaxRate__c > 0) amoutIncTaxprice += priceInfo.priceIncTaxNoService;
            if(sobj.TaxRate__c > 0) amoutIncTaxprice += priceInfo.priceIncTax;
            // 商品単価（税込、サービス込）
            item.unitPrice = priceInfo.unitPriceTax;
            // 英語の場合、英語名を再設定を行う
            if (isShowEnName) item.produceNm = sobj.Field7__r.ProductEnName__c;
            tran.add(item);
            
            // 2013/01/27 ADD/EDIT
            // 総金額合計計算
            amoutAllMoneyDetail += priceInfo.priceIncTax;
            // 特別税計算合計
            amoutIncSpecialPriceDetail += CommUtils.nullToZero(sobj.SpecialTax__c);
        }
        if (printType == ROOM_ONLY || printType == ROOM_FOOD || isGroupShowFlg) {
          amoutAllMoney = amoutAllMoneyDetail;
          amoutIncSpecialPrice = amoutIncSpecialPriceDetail;
          amoutIncDiscont = amoutIncDiscontDetail;
        }
        //integer len = MAX_SHOW_DETAIL_ROWS - tran.size();
        // サービス料金が存在する場合、明細へ追加する
        /*
      for (AccountAcount__c acc: account) {
        // サービス料（税込）情報を合計する
        amoutIncServicePrice += CommUtils.nullToZero(acc.SumSrvPriceIncTax__c);
      }
      if (amoutIncServicePrice > 0) {
          tran.add(new TranItem(new Tran1__c(
                          Field5__c = 'サービス料',
                         Field20__c = String.valueOf(amoutIncServicePrice),
                         Field21__c = '1',
                         RowNo__c = tran.size() + 1),
                         tran.size()+1));
      }*/

        if (amoutIncSpecialPrice > 0) {
            tran.add(new TranItem(new Tran1__c(
                                       Field5__c = (isShowEnName == true ? 'Accommodation Tax' : '宿泊税'),
                                       Field20__c = String.valueOf(amoutIncSpecialPrice),
                                       Field21__c = '1',
                                       RowNo__c = tran.size() + 1),
                                       tran.size()+1));
        }

        // 改ページ情報を設定する
    // 改ページ処理機能初期化
    allPageList = new List<OnePage>();
    Integer breakNum = PAGE_FIRSTPG_BREAK_RSNUM;
    for (Integer index =0; index < tran.size(); index++) {
      // 改ページ計算
      Integer breakLine = index - (allPageList.isEmpty() ? 0 : 1) * PAGE_FIRSTPG_BREAK_RSNUM - (allPageList.size() > 1 ? allPageList.size() -1 : 0 ) * PAGE_NEXTPG_BREAK_RSNUM;
      // 改ページする場合
      if (breakLine == 0) {
        OnePage onePg = new OnePage();
        onePg.addItem(tran[index]);
        allPageList.add(onePg);
        // ページ数を設定する
        onePg.currPages = allPageList.size();
      } else {
        OnePage onePg = allPageList[allPageList.size() - 1];
        onePg.addItem(tran[index]);
      }
    }

    Integer dumyLen = 0;
    OnePage dumyPage = null;
    // 明細データが非存在する場合
    if (allPageList.isEmpty()) {
      // だみデータ作成件数
            dumyLen = breakNum;
            dumyPage = new OnePage();
            allPageList.add(dumyPage);
    }
    // 全部データは一ページ場合、空白行を追加する
    if (allPageList.size() == 1) {
      dumyLen = breakNum - allPageList[0].onePageList.size();
      dumyPage = allPageList[0];
    }
        for (integer i=0; i < dumyLen; i++) {
          dumyPage.onePageList.add(new TranItem(new Tran1__c(), null));
        }
    // Header Pdf 情報を設定する[宿泊場合、設定を行う]
    if (account[0].Relreserve__c != null && account[0].Relreserve__r.RecordTypeId == CommLogicProcess.getLeadBookingRecType())
      this.setHeaderInfo(account[0].Relreserve__c);
    

    }
  /**
  * 発行日更新を行う
  **/
  public void extInitAction() {
      // 発行日更新処理を行う[2013/01/15 ADD BEGIN]
      List<Id> accIdLst = new List<Id>();
      for (AccountAcount__c acc: account) {
        accIdLst.add(acc.Id);
        //acc.IssueDate__c = Date.today();
      }
     // CommLogicProcess.writeLogInfo(accIdLst);
      // [2013/01/15 ADD END]
  }
  /**
  * レポートロゴ取得する
  **/
    public ReportLogo__c getReportLogo() {
      return CommRepUtils.getReplogoInfoByTypeId(CommRepUtils.REP_TYPE.LOGO_00_SYSDEF);
    }

    public AccountAcount__c getAccoutInfo() {
      return account[0];
    }
  
    //get Account#
    public string getAccountNo(){
        return account[0].name;
    }
  // get 請求書の宛名先名
  public String getAccountName() {
    String recpName = parMap.get('recpName');
    return CommUtils.isBlank(recpName) ? account[0].relaccount__r.Account.Name : recpName;
  }
    //get 'お客様'
    public string getCustomer(){
      /*
        if(account.relaccount__c!=null){
            return account.relaccount__r.name;
        }else{
            return '　　　　　　　　　　';
        }*/
        String cuName = parMap.get('cuName');
        return (CommUtils.isBlank(cuName) ? '　' : cuName);
    }

    //get '$売上計IV（税込）金額'
    public Decimal getCharge(){
      return amoutAllMoney;
      /*
        if ( account.Field151__c != null ) {
            //return putComma(string.valueof(account.Field151__c));
            return account.Field151__c;
        } else {
            return 0;
        }*/
    }

    //get Tax
    public Decimal getTax(){
      // 会計日付にて、消費税計算を行う[会計日付から税率を取得する][連泊場合：初日の税率で]
      // TODO:最後の会計日の消費税率で計算を行う
      Decimal taxRate = CommUtils.getTaxRate(account[0].Field148__c);
      //Map<Date, Decimal> rateMstmap = CommUtils.getTaxRateMap()
      // 消費税計算を行う：課税商品金額(税込) + サービス料(税込)　- 割引金額
        if ( amoutIncTaxprice > 0 ) {
            Decimal locAmoutIncTaxprice = amoutIncTaxprice
                               //+ CommUtils.nullToZero(amoutIncServicePrice)
                               - CommUtils.nullToZero(amoutIncDiscont);
            // TODO 消費税マスタの関連設定を再設定を行う
            return CommUtils.RoundProcess(locAmoutIncTaxprice / (1 + taxRate / 100) * (taxRate / 100), 0);
        } else {
            return 0;
        }
    }



    //get '$会計日付'
    public string getDate(){
        if ( account[0].Field148__c != null ) {
            string s = string.valueof(account[0].Field148__c)+' ';
            string year = s.substring(0,4);
            string month = s.substring(5,7);
            string day = s.substring(8,10);
            return  year+'年'+month+'月'+day+'日';
        } else {
            return  '    年'+'  月'+'  日';
        }
    }
    // 前受付金
    public Decimal getAdvancesReceived() {
      return amoutARprice;
    }
    //get '会計明細'
    public List<TranItem> getTran(){
        return tran;
    }
  // 割引合計
  public Decimal getAmoutIncDiscont() {
    return amoutIncDiscont;
  }
  // ご利用日
  public String getServiceDate() {
    return getAccoutInfo().Relreserve__r.EntryTime__c != null ? getAccoutInfo().Relreserve__r.EntryTime__c.format('yyyy年MM月dd日') : '    　  　　　';
  }
    public class TranItem {
      // 明細番号
      public Integer rowNo{get; private set;}
      // 商品名
      public String produceNm{get; private set;}
      // 価格
      public Decimal unitPrice{get; private set;}
      // 数量
      public Decimal quantity{get; private set;}
      // 利用日
      public String usedDate{get; private set;}

      public TranItem(Tran1__c sobj, Integer index) {
        rowNo = index;
        if (index == null) return;
        produceNm = sobj.Field5__c;
        unitPrice = CommUtils.nullToZero(sobj.Field20__c);
        quantity = CommUtils.nullToZero(sobj.Field21__c);
        //System.debug('RelAccount__c:' + sobj.RelAccount__r.Salesday__c);
        if (sobj.RelAccount__r.Salesday__c != null) {
          usedDate = (DateTime.newInstance(sobj.RelAccount__r.Salesday__c, Time.newInstance(0,0,0,0))).format('yyyy/MM/dd');
        }
      }
      public Boolean isShowInfo{get{return (rowNo != null);}}
    }

    // ヘーダ情報を設定する
    public void setHeaderInfo(String leadId) {
      // 2013/01/11 EDIT  Rroom__r.Rnumber__c -> Rroom__r.Name
      headInfo = [select id, Name, Rroom__r.Rnumber__c, Rroom__r.Name, 
        LeadIndexRef__r.DepartureDate__c, LeadIndexRef__r.EntryDate__c,
        LeadIndexRef__r.Nights__c, StayPersons__c From Lead__c where Id = :leadId];
    }
    public Lead__c headInfo{get; private set;}

}