Sforce8 Project Data/src/objects/Lead__c.object
<CustomObject>
    <description>予約台帳

Booking object: for one relation delete
1. Field283 &quot;(X5food5__c * chu4__c) +&quot; delete
2. X5food5__c delete
3. 昼料理５の通貨型の項目を追加して、昼料理５の金額を入力して頂くこと
4. タンザクレポートの昼料５項目のreplce</description>
    <fields>
        <fullName>CancelBool__c</fullName>
        <formula>If (ISPICKVAL( ReservedStatus__c , &quot;キャンセル&quot;) || ISPICKVAL( ReservedStatus__c , &quot;NO SHOW&quot;) || ISPICKVAL( ReservedStatus__c , &quot;削除&quot;) ,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>予約ステータスがキャンセルであれば1でなければ0を返す</inlineHelpText>
        <label>CancelBool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment3__c</fullName>
        <inlineHelpText>ご予約以降に、考慮すべき重要なことがら</inlineHelpText>
        <label>特記事項</label>
        <length>2048</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EntryTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>お客様が来られる予定の日付を選択してください。</inlineHelpText>
        <label>到着日</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field298__c</fullName>
        <inlineHelpText>チェックインへ変更することで、予約見積明細の内容が会計計上されます、連泊のお客様のときも日ごとにチェックインステータスへ変更する必要がありますのでご注意が必要です。</inlineHelpText>
        <label>お客様ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>チェックイン完</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>チェックアウト完</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>外出中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>入浴中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>滞在中</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field372__c</fullName>
        <formula>IF(
ISNULL(EntryTime__c),
&quot;&quot;,
CASE( MOD( DATEVALUE(EntryTime__c) - DATE(1900, 1, 7), 7),
0, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(日)&apos;,
1, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(月)&apos;,
2, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(火)&apos;,
3, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(水)&apos;,
4, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(木)&apos;,
5, TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(金) &apos;,
TEXT(YEAR(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(MONTH(DATEVALUE(EntryTime__c))) &amp; &quot;/&quot; &amp; TEXT(DAY(DATEVALUE(EntryTime__c))) &amp; &apos;(土)&apos;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$到着日</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receptiondate__c</fullName>
        <formula>DATEVALUE( ReservedDate__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$予約受付日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relcontact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>お客様</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>reservetg85</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReservedStatus__c</fullName>
        <label>予約ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>確認中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>確定</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>会場おさえ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>仮予約</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>キャンセルまち</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO SHOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>キャンセル</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>削除</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StayPersons__c</fullName>
        <defaultValue>1</defaultValue>
        <label>予約人数</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>checkoutdate__c</fullName>
        <formula>DATEVALUE(Departure__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>$出発日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>refTypeOfRooms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部屋タイプ</label>
        <referenceTo>TypeOfRooms__c</referenceTo>
        <relationshipLabel>ご予約</relationshipLabel>
        <relationshipName>typeOfRooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ご予約</label>
    <nameField>
        <label>予約名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sforce8 Project Data/src/classes/ContactBookingList.cls
/**
* 顧客に所属する予約データ一覧を表示する・一括キャンセル・一括チェックアウト
**/
public with sharing class ContactBookingList {

	/**
	* 検索条件変数定義する
	**/
	// 表示表示範囲日付（From）
	public String c_fromSearchDate{get;set;}
	public String c_toSearchDate{get;set;}
	// 過去データ表示フラグ
	public Boolean c_showHistoryFlg{get;set;}
	public Boolean topMsgShowFlg{get;set;}
	private String contactId;
	private List<BookingItem> leadInfoLst = new List<BookingItem>();
 	public ContactBookingList(ApexPages.StandardController stdController) {
        contactId = stdController.getId();
        initParameter();
        setQueryRsList();
    }
    private void initParameter() {
    	// 照会日付範囲はと今年から１年間予約データを表示する
    	DateTime nowTime = DateTime.now();
    	c_fromSearchDate = nowTime.format('yyyy/MM/dd');
    	c_toSearchDate = nowTime.addYears(1).format('yyyy/MM/dd');
    	c_showHistoryFlg = false;
    	topMsgShowFlg = false;
    	cancelSeason = 'キャンセル対応　' + UserInfo.getName();
    }

    // 検索条件有効性チェックを行う
    private Boolean preSetQueryRsList() {
    	try {
			Date dtfromSearchDate = Date.parse(c_fromSearchDate);
			Date dttoSearchDate = Date.parse(c_toSearchDate);
    	} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, '有効な日付を入力ください。'));
    		return false;
    	}
    	return true;
    }
    /**
    * 200件まで明細データを表示する
    **/
	public void setQueryRsList() {
		// 既存の検索結果をクリアする
		leadInfoLst.clear();
		// 有効性チェックを行う
		if (!preSetQueryRsList()) {
			topMsgShowFlg = true;
			return;
		} else topMsgShowFlg = false;
		// 該当ユーザーに関連付け予約一覧リストを取得する
		// 予約ステータス And お客様ステータス:
		//Date todayDt = Date.today();
		Date dtfromSearchDate = Date.parse(c_fromSearchDate);
		Date dttoSearchDate = Date.parse(c_toSearchDate);

		String strQuery = strSelect + createWhere() + createOrder();
//System.debug('strQuery: ' + strQuery);
//System.debug('contactId:' + contactId);
//System.debug('dtfromSearchDate:' + dtfromSearchDate);
//System.debug('dttoSearchDate:' + dttoSearchDate);
		for (Lead__c leadItem: Database.query(strQuery)) {
			BookingItem item = new BookingItem(leadItem);
			leadInfoLst.add(item);
		}
	}
	/**
	* 一括予約キャンセル処理成功を行う
	**/
	// キャンセル理由
	public String cancelSeason{get; set;}
	public void batchCancelProc() {
//System.debug('batchCancelProc:Reason:' + cancelSeason);

		// 選択対応データから、ステータス更新を行う
		List<Lead__c> updList = new List<Lead__c>();
		for (BookingItem item: leadInfoLst) {
			// 非選択されている場合、SKIPする
			if (!item.isSelected) continue;
			// すでにキャンセル済みデータは対象外
			if (item.sobj.CancelBool__c == CommConst.LEAD_ST_CANCEL_FLG) continue;
			// 顧客データステータスはチェッキン完了またはチェックアウト場合、対象外？
			// TODO?
			// キャンセルステータスを設定を行う
			item.sobj.ReservedStatus__c = CommConst.LEAD_ST_CANCEL;
			// 特記事項にキャンセル理由を追加する
// System.debug('cancelSeason:' + cancelSeason);
			item.sobj.Comment3__c = CommUtils.nullToBlank(item.sobj.Comment3__c) + '\n' + cancelSeason;
			updList.add(item.sobj);
		}
		// 更新処理を行う
		try {
// System.debug('updList:' + updList);
			update updList;
		} catch (Exception e) {
			System.debug(e.getMessage());
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		// 最新情報を取得する
		this.setQueryRsList();
	}
	/**
	* 一括チェックアウト処理を行う
	**/
	public void batchCheckoutProc() {
		// 選択対応データから、ステータス更新を行う
		List<Lead__c> updList = new List<Lead__c>();
		for (BookingItem item: leadInfoLst) {
			// 非選択されている場合、SKIPする
			if (!item.isSelected) continue;
			// すでにキャンセル済みデータは対象外
			if (item.sobj.CancelBool__c == CommConst.LEAD_ST_CANCEL_FLG) continue;
			// 顧客データステータスはチェッキン完了またはチェックアウト場合、対象外？
			if (item.sobj.Field298__c == CommConst.LEAD_GUEST_ST_CO) continue;
			// TODO?
			// お客様ステータスにチェックアウトを設定する
			item.sobj.Field298__c = CommConst.LEAD_GUEST_ST_CO;
			updList.add(item.sobj);
		}
		// 更新処理を行う
		try {
			update updList;
		} catch (Exception e) {
			System.debug(e.getMessage());
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		// 最新情報を取得する
		this.setQueryRsList();
	}

	public List<BookingItem> getLeadInfoLst() {
		return this.leadInfoLst;
	}
	private final String strSelect = 'select id, name, CancelBool__c, Field372__c,checkoutdate__c,ReservedStatus__c, Field298__c,Receptiondate__c,refTypeOfRooms__c,StayPersons__c from Lead__c ';
	/**
	* 画面検索条件を作成する
	**/
	private String createWhere() {
		String strWhere = ' Where Relcontact__c = :contactId ';
		if (!CommUtils.isBlank(c_fromSearchDate)) strWhere+= ' And DAY_ONLY(convertTimezone(EntryTime__c)) >= :dtfromSearchDate ';
		if (!CommUtils.isBlank(c_toSearchDate)) strWhere+= ' And DAY_ONLY(convertTimezone(EntryTime__c)) <= :dttoSearchDate ';
		// すべてデータを表示する場合
		if (!c_showHistoryFlg) strWhere+= ' And CancelBool__c != ' + CommConst.LEAD_ST_CANCEL_FLG;
		return strWhere;
	}
	/**
	* 並び順情報を取得する
	**/
	private String createOrder() {
		String strOrder = ' Order By EntryTime__c asc limit 200 ';
		return strOrder;
	}

	public class BookingItem {
		public 	BookingItem(Lead__c psobj) {
			sobj = psobj;
			isSelected = false;
		}
		// 予約情報格納する
		public Lead__c sobj{get; private set;}
		public Boolean isSelected{get; set;}
	}

	/**
	* 有効性チェックを行う
	**/
	static testMethod void testCase1() {
		Lead__c lead1 = TestCommon.createLead();
		Contact refContact = [select id from Contact where id =:lead1.Relcontact__c];
		ApexPages.StandardController scontrol = new ApexPages.StandardController(refContact);
		// 一括キャンセル処理を行う
		ContactBookingList ctrl = new ContactBookingList(scontrol);
		ctrl.c_fromSearchDate = '1A';
		ctrl.c_toSearchDate = '2C';
		ctrl.batchCheckoutProc();
		ctrl.batchCancelProc();
		System.assert(ctrl.getLeadInfoLst() != null);
	}
	static testMethod void testCase2() {
		Lead__c lead1 = TestCommon.createLead();
		Contact refContact = [select id from Contact where id =:lead1.Relcontact__c];
		ApexPages.StandardController scontrol = new ApexPages.StandardController(refContact);
		// 一括キャンセル処理を行う
		ContactBookingList ctrl = new ContactBookingList(scontrol);
		List<ContactBookingList.BookingItem> rs = ctrl.getLeadInfoLst();
		rs[0].isSelected = true;
		ctrl.batchCheckoutProc();
		rs = ctrl.getLeadInfoLst();
		rs[0].isSelected = true;
		ctrl.batchCancelProc();
		System.assert(ctrl.getLeadInfoLst() != null);
	}
}